#!/bin/bash

# LogicGuard Deployment Script

set -e

echo "LogicGuard Deployment Starting..."

# Get server IP
SERVER_IP=$(curl ifconfig.me| awk '{print $1}')
echo " Detected Server IP: $SERVER_IP"

# Ask for confirmation
read -p "Deploy with IP $SERVER_IP? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Deployment cancelled"
    exit 1
fi

# Backup current .env files
echo "Backing up current configs..."
cp backend/.env backend/.env.backup.$(date +%Y%m%d_%H%M%S) 2>/dev/null || true
cp frontend/.env.production frontend/.env.production.backup.$(date +%Y%m%d_%H%M%S) 2>/dev/null || true

# Update backend/.env
echo "Updating backend/.env..."
if [ -f backend/.env ]; then
    # Update FRONTEND_URL
    sed -i "s|^FRONTEND_URL=.*|FRONTEND_URL=http://${SERVER_IP}:3000|" backend/.env
    
    # Update or add ALLOWED_ORIGINS
    if grep -q "^ALLOWED_ORIGINS=" backend/.env; then
        sed -i "s|^ALLOWED_ORIGINS=.*|ALLOWED_ORIGINS=http://${SERVER_IP}:3000,http://localhost:3000|" backend/.env
    else
        echo "ALLOWED_ORIGINS=http://${SERVER_IP}:3000,http://localhost:3000" >> backend/.env
    fi
    
    echo "Backend config updated"
else
    echo "backend/.env not found! Copy from backend/.env.example first"
    exit 1
fi

# Update frontend/.env.production (optional)
echo "Updating frontend/.env.production..."
cat > frontend/.env.production << EOF
# Production/Server API Configuration
# Auto-generated by deploy.sh on $(date)
NEXT_PUBLIC_API_URL=http://${SERVER_IP}:8000/api
EOF
echo "Frontend config updated"

# Show current configs
echo ""
echo "Current Configuration:"
echo "=========================="
echo "Backend CORS:"
grep -E "^FRONTEND_URL=|^ALLOWED_ORIGINS=" backend/.env
echo ""
echo "Frontend API URL:"
cat frontend/.env.production
echo "=========================="
echo ""

# Deploy with docker compose
echo "Deploying with Docker Compose..."
docker compose down
docker compose up -d --build

# Wait for services to start
echo "Waiting for services to start..."
sleep 5

# Check service status
echo ""
echo "Service Status:"
docker compose ps

# Check backend CORS
echo ""
echo "Checking Backend CORS Configuration:"
docker logs logicguard_backend 2>&1 | grep "Allowed CORS" | tail -1

# Health checks
echo ""
echo "Health Checks:"
echo -n "Backend API: "
curl -s http://localhost:8000/health | grep -q "healthy" && echo "✅ OK" || echo "❌ FAILED"

echo -n "Frontend: "
curl -s http://localhost:3000 > /dev/null && echo "✅ OK" || echo "❌ FAILED"

# Show access URLs
echo ""
echo "Deployment Complete!"
echo "=========================="
echo "📱 Access URLs:"
echo "   Frontend: http://${SERVER_IP}:3000"
echo "   Backend API: http://${SERVER_IP}:8000"
echo "   API Docs: http://${SERVER_IP}:8000/docs"
echo ""
echo "   Localhost Frontend: http://localhost:3000"
echo "   Localhost Backend: http://localhost:8000"
echo "=========================="
echo ""
echo "Tips:"
echo "   - View logs: docker compose logs -f"
echo "   - Stop services: docker compose down"
echo "   - Restart: docker compose restart"
echo ""
